<a href="https://colab.research.google.com/github/freddy-7/TI2001B-2023/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#GOOGLE COLAB
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO XLSX

In [5]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_csv('los-angeles.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43932 entries, 0 to 43931
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              43932 non-null  int64
 1   name                            43932 non-null  str
 2   host_id                         43751 non-null  float64
 3   host_profile_id                 43537 non-null  float64
 4   host_name                       43548 non-null  str
 5   neighbourhood_group             43932 non-null  str
 6   neighbourhood                   43932 non-null  str
 7   latitude                        43932 non-null  float64
 8   longitude                       43932 non-null  float64
 9   room_type                       43932 non-null  str
 10  price                           38362 non-null  float64
 11  minimum_nights                  43921 non-null  float64
 12  number_of_reviews               43932 non-null  int64
 13  last_review                     32621 non-null  str
 14  reviews_per_month               32621 non-null  float64
 15  calculated_host_listings_count  43751 non-null  float64
 16  availability_365                43932 non-null  int64
 17  number_of_reviews_ltm           43932 non-null  int64
 18  license                         13192 non-null  str
dtypes: float64(8), int64(4), str(7)
memory usage: 6.4 MB

In [ ]:
inciso1=df[(df["CVE_CLPV"] >= 1000) & (df["CVE_CLPV"] <= 2000)]
inciso1

In [ ]:
inciso2=df[~(df["CVE_VEND"].isin([5, 4]))]
inciso2

In [ ]:
inciso3=df[(df["FECHA_ENT"] == "2022-02-28 00:00:00")]
inciso3

In [ ]:
inciso4=df[(df["CAN_TOT"] > 5951.7) | (df["STATUS"] == "E")]
inciso4

In [ ]:
inciso5=df.iloc[:, [1] + [7] + [8] + [10]]
inciso5

In [ ]:
inciso6=df.iloc[list(range(7001, 8000)), :]
inciso6

In [ ]:
inciso_a=df["host_name"].drop_duplicates().head(5)
inciso_a

In [ ]:
# No existe columna de "host_since" en mi lista de Los Angeles. Voy a usar "last_review" después de 2020
inciso_b=df[df["last_review"] > "2020-12-31"]
inciso_b

In [ ]:
# Inciso C: No existe columna de "host_response_time" en mi lista de Los Angeles.

In [ ]:
inciso_d=df[200::200]
inciso_d

In [ ]:
inciso_e=df[(df["room_type"] == "Entire home/apt") | (df["room_type"] == "Private room")]
inciso_e

In [ ]:
# Inciso F: No existe una columna que me indique cuantas camas hay en mis datos.

In [ ]:
# Inciso G: No existe una columna que me indique si un socio es "superhost".

In [ ]:
inciso_h=df.iloc[: , 1::2]
inciso_h

In [8]:
df1= pd.read_csv('los-angeles.csv')
df1

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2708,"Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...",3008.0,1.462506e+18,⁨Chas.⁩,City of Los Angeles,Hollywood,34.096250,-118.346050,Private room,67.0,30.0,47,2026-05-26,0.32,2.0,301,3,NaN
1,2732,Zen Life at the Beach,3041.0,1.462506e+18,Yogapriestess,Other Cities,Santa Monica,34.004400,-118.480950,Private room,214.0,1.0,24,2022-08-21,0.13,2.0,350,0,228269
2,6033,Poolside Serenity Studio,11619.0,1.462507e+18,Sarah,City of Los Angeles,Woodland Hills,34.168870,-118.644780,Entire home/apt,100.0,30.0,19,2020-03-22,0.09,7.0,270,0,NaN
3,6931,"RUN Runyon, Beau Furn Rms Terrace Hollyw Hill ...",3008.0,1.462506e+18,⁨Chas.⁩,City of Los Angeles,Hollywood,34.096260,-118.343720,Private room,95.0,30.0,39,2025-12-15,0.19,2.0,259,2,NaN
4,7874,HD Wi-Fi E Bellflower Cerritos Lakewood LB LA,21700.0,1.462507e+18,Henry,Other Cities,Bellflower,33.876870,-118.114440,Private room,113.0,1.0,26,2026-04-02,0.29,4.0,103,9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43927,1707678777570851520,The French Lime Pool House - Sleeps 8 - Air ho...,588675098.0,1.463893e+18,Posh,Unincorporated Areas,Desert View Highlands,34.587350,-118.160880,Entire home/apt,220.0,2.0,0,NaN,NaN,13.0,361,0,NaN
43928,1707701464310658544,Hollywood City Views The Godfrey,383724181.0,1.469787e+18,Upscale LA,Other Cities,West Hollywood,34.093596,-118.343729,Entire home/apt,399.0,3.0,0,NaN,NaN,14.0,361,0,Exempt
43929,1707712658970417218,Spacious Waterfront 3BR Marina Retreat,412269286.0,1.469879e+18,Tee,Unincorporated Areas,Marina del Rey,33.976153,-118.452329,Entire home/apt,927.0,14.0,0,NaN,NaN,1.0,365,0,NaN
43930,1707714248958928308,Zen in Hollywood Walk of Fame,383724181.0,1.469787e+18,Upscale LA,Other Cities,West Hollywood,34.093596,-118.343729,Entire home/apt,532.0,1.0,0,NaN,NaN,14.0,361,0,Exempt
43931,1707753561170835767,West Hills Oasis,382786700.0,1.469784e+18,Azita,Other Cities,Calabasas,34.140982,-118.653587,Entire home/apt,296.0,1.0,0,NaN,NaN,3.0,363,0,NaN

In [110]:
inciso7=df1.loc[[1, 2], ["FECHAELAB"]]
inciso7

                        FECHAELAB
CVE_VEND
1.0       2019-09-03 08:58:42.000
1.0       2019-09-03 09:55:14.000
1.0       2019-09-03 13:25:33.000
1.0       2019-09-03 13:33:23.000
1.0       2019-09-04 09:15:12.000
...                           ...
2.0       2023-03-06 16:09:39.013
2.0       2023-03-06 16:38:42.933
2.0       2023-03-06 17:02:33.390
2.0       2023-03-07 12:43:49.567
2.0       2023-03-07 12:45:58.407

[8665 rows x 1 columns]

In [ ]:
#Verificamos información del DataFrame
df.info()
df.head(5)

ITERACIÓN

**Iterar columnas directamente del dataframe**

In [ ]:
# Iterar sobre la columna 'nombre'
for nombre in df['NOMBRE']:
    print(nombre)

***USANDO NUMPY***

**Iterar columnas tipo STRING**

In [ ]:
# Iterar sobre una columna tipo string: 'NOMBRE' con Numpy
nombres = df['NOMBRE'].to_numpy() #Primero convertimos la columna en un array

# Iterar sobre el array
for nombre in np.nditer(nombres, flags=['refs_ok']): #Usamos flags=['refs_ok'] si la columna contiene strings (objetos) en lugar de números
    print(nombre.item())  # item() lo convierte a string nativo de Python

**Iterar columnas tipo NUMÉRICO**

In [ ]:
# Iterar sobre una columna tipo numérico: 'MONTO ADEUDADO' con Numpy
monto_adeudado = df['MONTO ADEUDADO'].to_numpy() # Convertir la columna 'MONTO ADEUDADO' a array de NumPy

# Iterar sobre el array
for monto_adeudado in np.nditer(monto_adeudado):
    print(monto_adeudado)  # monto_adeudado es directamente un número (int o float)

**Iterar Filas**

In [ ]:
# Iterar sobre cada fila del dataframe
for index, row in df.iterrows():
    print(f"Fila {index}:")
    print(f"NOMBRE: {row['NOMBRE']}")
    print(f"FECHA DE VENCIMIENTO: {row['FECHA_VENCIMIENTO']}")
    print("-----")

**OPERACIONES FUNDAMENTALES**

In [ ]:
#Convertir cada nombre a mayúsculas
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.upper())

In [ ]:
#Convertir cada nombre a minúsculas
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.lower())

In [ ]:
#Convertir la primera letra del registro en mayúscula
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.capitalize())

In [ ]:
#Convertir la primera letra de cada palabra en mayúscula
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.title())

In [ ]:
#Contar cuántas letras tiene cada nombre
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre, "tiene", len(nombre), "letras")

In [ ]:
#Mostrar solamente los nombres que tienen menos de 15 letras
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    
    if len(nombre) < 15:
        print(nombre)

In [ ]:
#Crear un saludo para cada nombre
def saludar(nombre):
    return "Hola " + nombre + ", bienvenid@!"

for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(saludar(nombre))

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [ ]:
#Filtro por objeto
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

In [ ]:
#Filtro por filas
#filtro2= df.iloc[3:11,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
filtro2= df.iloc[ [0] + list(range(10, 14)) + [50] , : ]  #Filas combinadas
filtro2

In [ ]:
#Filtro por columnas
#filtro3=df.iloc[ : , 0:3]       #Columnas consecutivas
#filtro3=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas
filtro3= df.iloc[ :, [0] + list(range(1, 4)) + [5] ]  #Filas combinadas
filtro3

In [ ]:
#GOOGLE COLAB
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

In [ ]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1)
df1

In [ ]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

In [ ]:
#Filtro por cabecera
filtro5=df.head()
filtro5

In [ ]:
#Filtro por cola
filtro5=df.tail()
filtro5

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [ ]:
#Filtro por comparacion
filtro6=df[df["MONTO ADEUDADO"] == 1000]
filtro6

**FILTROS BASICOS CON CONETORES LOGICOS**

In [ ]:
#Filtro Y (&)
filtro7=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro7

In [ ]:
#Filtro o (|)
filtro8=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

In [ ]:
#Filtro not (~)
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000)]
filtro9

In [39]:
#Convertir archivo filtrado a CSV
inciso_h.to_csv("Inciso_h.csv")

In [ ]:
#GOOGLE COLAB
#descardar archivo filtrado en csv
from google.colab import files


files.download("Entregable1.csv")